version: '3.8'
services:
  ultrakill-web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - START_SECRET=supersecret
    volumes:
      - ./ULTRAKILL.exe:C:\app\ULTRAKILL.exe
      - ./config.yml:C:\app\config.yml
